{% set name = "fastjsonschema" %}
{% set version = "2.14.5" %}

package:
  name: python-{{ name }}
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: afbc235655f06356e46caa80190512e4d9222abfaca856041be5a74c665fa094
  - folder: src
    url: https://github.com/horejsek/python-{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 0209de91f74db5fa93d67164d594d16af93e63358630bfe99cc2cd3cc7d4a6b2

build:
  noarch: python
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.3
    - pip
  run:
    - python >=3.3

test:
  source_files:
    - src/tests
  requires:
    - pytest-cov
    - pytest-benchmark
  imports:
    - fastjsonschema
  commands:
    - cd src && cd tests && pytest --cov fastjsonschema -k "not compile_to_code_ipv6_regex"

about:
  home: https://github.com/horejsek/python-fastjsonschema
  license: BSD-3-Clause
  license_family: BSD
  license_file: src/LICENSE
  summary: Fastest Python implementation of JSON schema
  description: |
    fastjsonschema implements validation of JSON documents by JSON schema. The
    library implements JSON schema drafts 04, 06 and 07. The main purpose is to
    have a really fast implementation.
  doc_url: https://horejsek.github.io/python-fastjsonschema
  doc_source_url: https://github.com/horejsek/python-fastjsonschema/tree/master/docs

extra:
  recipe-maintainers:
    - bollwyvl
