{% set version = "2.21.2" %}

{% set python_min = python_min | default("3.9") %}

package:
  name: python-fastjsonschema
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/f/fastjsonschema/fastjsonschema-{{ version }}.tar.gz
    sha256: b1eb43748041c880796cd077f1a07c3d94e93ae84bba5ed36800a33554ae05de
  - folder: src
    url: https://github.com/horejsek/python-fastjsonschema/archive/v{{ version }}.tar.gz
    sha256: 3757b049728580d516c0af50e11eed050c8e2c1815b221954c635bde455dcc78

build:
  noarch: python
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  source_files:
    - src/tests
  requires:
    - pip
    - pytest-benchmark
    - coverage
    - python {{ python_min }}
  imports:
    - fastjsonschema
  commands:
    - pip check
    - cd src/tests
    - coverage run --source fastjsonschema -m pytest -vv --tb=long --color=yes -k "not (compile_to_code_ipv6_regex or compile_to_code_custom_format_with_refs)"
    - coverage report --show-missing --skip-covered --fail-under 87

about:
  home: https://github.com/horejsek/python-fastjsonschema
  license: BSD-3-Clause
  license_family: BSD
  license_file: src/LICENSE
  summary: Fastest Python implementation of JSON schema
  description: |
    fastjsonschema implements validation of JSON documents by JSON schema. The
    library implements JSON schema drafts 04, 06 and 07. The main purpose is to
    have a really fast implementation.
  doc_url: https://horejsek.github.io/python-fastjsonschema
  doc_source_url: https://github.com/horejsek/python-fastjsonschema/tree/master/docs

extra:
  recipe-maintainers:
    - bollwyvl
