# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 2.21.2

package:
  name: python-fastjsonschema
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/f/fastjsonschema/fastjsonschema-${{ version }}.tar.gz
    sha256: b1eb43748041c880796cd077f1a07c3d94e93ae84bba5ed36800a33554ae05de
    target_directory: dist
  - url: https://github.com/horejsek/python-fastjsonschema/archive/v${{ version }}.tar.gz
    sha256: 3757b049728580d516c0af50e11eed050c8e2c1815b221954c635bde455dcc78
    target_directory: src

build:
  number: 0
  noarch: python
  script:
    - cd dist
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports: fastjsonschema
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - files:
      source:
        - src/tests/
    requirements:
      run:
        - coverage
        - pytest-benchmark
        - python ${{ python_min }}.*
    script:
      - cd src/tests
      - coverage run --source fastjsonschema -m pytest -vv --tb=long --color=yes -k "not (compile_to_code_ipv6_regex or compile_to_code_custom_format_with_refs)"
      - coverage report --show-missing --skip-covered --fail-under 87

about:
  license: BSD-3-Clause
  license_file: src/LICENSE
  summary: Fastest Python implementation of JSON schema
  description: |
    fastjsonschema implements validation of JSON documents by JSON schema. The
    library implements JSON schema drafts 04, 06 and 07. The main purpose is to
    have a really fast implementation.
  homepage: https://github.com/horejsek/python-fastjsonschema
  documentation: https://horejsek.github.io/python-fastjsonschema

extra:
  recipe-maintainers:
    - bollwyvl
